version: "3"

services:

  app:
    image: api-app
    container_name: api-app
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - /var/www/logs:/vol/logs
      - /var/www/static:/vol/web/static
      - /var/www/media:/vol/web/media
    env_file:
      - .env
    environment:
      - ENV=${ENV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

